[package]
name = "na-mainloop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#log = "0.4"
#android_logger = "0.11.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "fmt",
    "env-filter",
    "tracing-log",
] }
paranoid-android = "0.2"
tracing-log = "0.2"

android-activity = { version = "0.6", features = ["native-activity"] }
jni = "0.22"

[lib]
#name="na_mainloop"
crate-type = ["cdylib"]

####################
# cargo apk config #
####################

[package.metadata.android]
package = "com.github.rust_mobile.namainloop"
#
[package.metadata.android.sdk]
min_sdk_version = 31
target_sdk_version = 35

[package.metadata.android.application]
label = "NativeActivity Mainloop"
