[package]
name = "na-winit-glutin"
version = "0.1.0"
edition = "2021"


[features]
default = ["egl", "glx", "x11", "wayland", "wgl"]

desktop = []

egl = ["glutin/egl"]
glx = ["glutin/glx", "glutin/x11", "winit/x11", "x11"]
wgl = ["glutin/wgl"]
x11 = ["glutin/x11", "winit/x11"]
wayland = [
    "glutin/wayland",
    "winit/wayland",
    "winit/wayland-dlopen",
    "winit/wayland-csd-adwaita-notitle",
]


[dependencies]
log = "0.4"
winit = { version = "0.30", features = ["android-native-activity"] }
glutin = "0.32"
raw-window-handle = "0.6.0"

[target.'cfg(not(target_os = "android"))'.dependencies]
env_logger = "0.10"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.11.0"

[build-dependencies]
gl_generator = "0.14"
cfg_aliases = "0.2"

[lib]
#name="main"
crate-type = ["cdylib"]

[[bin]]
path = "src/lib.rs"
name = "test-winit-glutin"
required-features = ["desktop"]
