[package]
name = "agdk-egui"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#log = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [
    "fmt",
    "env-filter",
    "tracing-log",
] }
pollster = "0.2"

egui = { version = "0.33" }
egui-wgpu = { version = "0.33", features = ["winit"] }
egui-winit = { version = "0.33", default-features = false, features = [
    "wayland",
    "android-game-activity",
] }
egui_demo_lib = "0.33"
winit = { version = "0.30.12" }

[target.'cfg(not(target_os = "android"))'.dependencies]
env_logger = "0.10"

[target.'cfg(target_os = "android")'.dependencies]
#android_logger = "0.13.0"
#tracing-android = "0.2.0"
paranoid-android = "0.2"
tracing-log = "0.2"

[features]
default = []
desktop = []

[lib]
name = "main"
crate-type = ["cdylib"]

[[bin]]
path = "src/lib.rs"
name = "egui-test"
required-features = ["desktop"]

[patch.crates-io]
#egui = { version = "0.22", path = "../../egui/crates/egui" }
#egui-wgpu = { version = "0.22", path = "../../egui/crates/egui-wgpu" }
#egui-winit = { version = "0.22", path = "../../egui/crates/egui-winit" }
#android-activity = { path = "../../android-activity/android-activity" }
#jni = { path = "../../../../jni-rs/jni-git-dev0/crates/jni" }
#winit = { path = "../../../../winit/winit-0.30.x" }

android-activity = { git = "https://github.com/rust-mobile/android-activity", branch = "rib/stack/ime-support" }
winit = { git = "https://github.com/rib/winit", branch = "rib/pr/android-ime-0.30" }
